#!/bin/bash

# Read each word and its length into a new file
awk '{ print length, $0 }' words.txt > words_with_lengths.txt

# Loop through unique lengths and save words with each length into separate files
for length in $(awk '{print $1}' words_with_lengths.txt | sort -nu); do
    grep "^$length " words_with_lengths.txt | cut -d' ' -f2- > "$((length - 1))"
done

# Clean up temporary file
rm words_with_lengths.txt

echo "Words sorted into files based on their lengths."
